# Generated by Django 2.2.7 on 2019-11-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('joined_at', models.DateField(verbose_name='Joined At')),
                ('disjoined_at', models.DateField(blank=True, null=True, verbose_name='Disjoined At')),
                ('membership_type', models.CharField(max_length=50, verbose_name='Membership Type')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Birthday')),
            ],
            options={
                'verbose_name': 'teammate',
                'verbose_name_plural': 'teammates',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='teammate',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique-person'),
        ),
        migrations.AddField(
            model_name='membership',
            name='teammate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teammate.Teammate', verbose_name='Teammate'),
        ),
    ]
